# Generated by Django 2.0.13 on 2019-11-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='produtos',
            new_name='produto',
        ),
    ]
