# Generated by Django 2.0.13 on 2019-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('descricao', models.CharField(default='', max_length=600)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('idade', models.IntegerField(default=1)),
                ('tamanho', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('raca', models.CharField(default='', max_length=100)),
                ('localizacao', models.CharField(default='', max_length=200)),
                ('castrado', models.BooleanField(default=False)),
                ('filhos', models.BooleanField(default=False)),
                ('irmaos', models.BooleanField(default=False)),
                ('fiv', models.BooleanField(default=False)),
                ('felv', models.BooleanField(default=False)),
                ('doente', models.BooleanField(default=False)),
                ('doencas', models.CharField(blank=True, default='', max_length=200)),
                ('vacinado', models.BooleanField(default=False)),
                ('raiva', models.BooleanField(default=False)),
                ('vermifugado', models.BooleanField(default=False)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('descricao', models.CharField(default='', max_length=600)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('likes', models.IntegerField(default=1)),
                ('dislikes', models.IntegerField(default=1)),
                ('quantidade', models.IntegerField(default=1)),
                ('marca', models.CharField(default='', max_length=150)),
                ('fabricante', models.CharField(default='', max_length=150)),
                ('dimensoes', models.CharField(default='', max_length=100)),
                ('peso', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('garantia', models.IntegerField(default=0)),
                ('cor', models.CharField(default='', max_length=100)),
                ('material', models.CharField(default='', max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
