# Generated by Django 2.0.13 on 2019-10-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='doente',
        ),
    ]
