# Generated by Django 2.0.13 on 2019-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_gato_doente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gato',
            name='imagem',
            field=models.ImageField(upload_to='gatos'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos'),
        ),
    ]
